allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': false
  esbuild: true
  prisma: true
fetchTimeout: 600000
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
ignoredBuiltDependencies:
  - '@sentry/cli'
